"""Agregando columna comprobante_pago

Revision ID: 5bc379b57be9
Revises: 35d8a674c361
Create Date: 2026-03-08 03:38:48.474469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc379b57be9'
down_revision = '35d8a674c361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprobante_pago', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('comprobante_pago')

    # ### end Alembic commands ###
